# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ui.author_controller:
        class: FractalizeR\LibrarianBundle\UI\Domain\Author\Controller\AuthorController
        arguments:
          - '@logic.author_repository'
        calls:
          - [setContainer, ['@service_container']]

    ui.article_controller:
        class: FractalizeR\LibrarianBundle\UI\Domain\Article\Controller\ArticleController
        arguments:
          - '@logic.article_repository'
        calls:
          - [setContainer, ['@service_container']]

    logic.article_repository:
        class: FractalizeR\LibrarianBundle\Logic\Domain\Article\Repository\ArticleRepository
        factory: ['@doctrine', 'getRepository']
        arguments:
            - FractalizeR\LibrarianBundle\Logic\Domain\Article\Entity\Article

    logic.author_repository:
        class: FractalizeR\LibrarianBundle\Logic\Domain\Author\Repository\AuthorRepository
        factory: ['@doctrine', 'getRepository']
        arguments:
            - FractalizeR\LibrarianBundle\Logic\Domain\Author\Entity\Author